import Head from "next/head";
import AppWrapper from "~/common/components/AppWrapper";

export default function Home() {
  return (
    <>
      <Head>
        <title>Phasmophobia Guide</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppWrapper />
    </>
  );
}
